server:
  servlet:
    context-path: /funcionarios/api

    spring:
      datasource:
        url: jdbc:h2:mem:demondb
        password:
          driver-class-name: org.h2.Driver

          h2:
            console:
              enabled: true
              path: /h2-console
